language: python
sudo: required
services:
- docker
before_install:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker run --rm --privileged multiarch/qemu-user-static:register
install:
- docker build --rm --no-cache -t stevebargelt/mosquitto-rpi .
- docker push stevebargelt/mosquitto-rpi
script: true
notifications:
  slack:
    rooms:
      secure: QsErPkGgb4En1bpGechrKEdodYhhCLS7N7AW2WJEmghAvKlsLet0T980LAj6ZLDRHY5IMwujMkh7hCKizabjai3gGAzBV58cd7Ixel0s409S4x/nHsetSlrSV/llDemYzY2fMIy/XzGXzSxrTp8X9iCdC5CB+fGlY5kQgKURQ5Z2o4G2cwXAAwQHAfjh5k8QIDHYv4ou1EuKajD9uVyIkgkq6zMfWqLYei7pLEuEn82yXWoCHZKcTLvd1WbgVSFLW3D1iKtC7WLWACOO3CbYi45s2QmVwACxd+ygyuX/Ja5EElmbsdyRBPLpNj9eSZ3PkWnga8sNG3R1jjjIUpMlmzW8RH7D/qpy9NaJRwYMWaD3XTXsxIcS/iKrxpVnFx1YHn9rQ3Z6V2KfSNZSNiK3HiPrjs3QZ6cRw/R0mbbD92kgoTZPUbXVwobcCrejqwrGySiqB98TRouMIdML1AnZ4dB9WTlZfqgnIzubPKGYYDLY+cV1LzBUXfbF+3ochU94YRJnqocKY6sy+YLoPVZoyyL1oB//lDsqc14ormLRsQdy/dumBTc4XE4dny5UhtVpYIrzIXmb/d2ghrH2biEOjb32chPycnXxwXqq59OUzSQAUTgkOG+D7+X5LMlFRa2NCJfn9abfxe5n0AKYOjxLYyU1y2fFhgsBFrNPepYMvI8=
    template:
    - Status=%{result}, Job=%{repository_name}, Build=%{build_number}, URL=%{build_url},
      HUB=https://hub.docker.com/r/stevebargelt/mosquitto-rpi/
    on_success: change
    on_failure: always