language: python
sudo: required

services:
  - docker

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker run --rm --privileged multiarch/qemu-user-static:register

install:
  - docker build --rm --no-cache -t stevebargelt/mosquitto-rpi .
  - docker push stevebargelt/mosquitto-rpi

script: true

notifications:
  slack:
    rooms:
      - bargelt:r8ZuK4YKz8rPmOfPZ07pFF49#general
    template:
      - "Status=%{result}, Job=%{repository_name}, Build=%{build_number}, URL=%{build_url}, HUB=https://hub.docker.com/r/stevebargelt/mosquitto-rpi/"